version: "3.4"

services:
  challengecoodeshbackend:
    image: challengecoodeshbackend
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    volumes:
      - .:/app
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: 